"""Post-approval write-back into Grafana Cloud.

An investigation that only reads leaves the people who own the dashboard with no
record that anything happened. Once a supervisor approves a remediation, the run
writes it back where an SRE would actually look: an annotation on the Grafana
timeline marking what was changed and why, and, when a delivery is at risk, a
Grafana incident carrying the same summary.

Two properties matter here.

The writes run only after a human has approved, and their arguments are built in
this module from the approval record rather than generated by the model. The
agent's own tool surface reaches the gateway's read-only /call path, which
rejects every write tool by name, so nothing the model emits can reach Grafana
with a write however the prompt is manipulated.

And every write is best-effort. The remediation has already been applied to the
control plane by the time these run, so a Grafana outage must not turn a
successful rollback into a reported failure. Failures are logged, returned in the
result for the audit record, and otherwise ignored.
"""
from __future__ import annotations

import time
from typing import Any, Dict, List, Optional

import httpx

from src.config import settings
from services.common.telemetry import setup_logging

logger = setup_logging("action-executor-grafana")


class GrafanaWriteBack:
    """Writes approved remediations back to Grafana through the MCP gateway."""

    def __init__(self) -> None:
        self._http_client = httpx.AsyncClient(timeout=15.0)

    async def _write(
        self,
        tool_name: str,
        parameters: Dict[str, Any],
        tenant_id: str,
        run_id: str,
        approval_id: str,
    ) -> Dict[str, Any]:
        """Invokes one write tool on the gateway's approval-gated /write path."""
        response = await self._http_client.post(
            f"{settings.mcp_gateway_url}/write",
            json={
                "tool_name": tool_name,
                "parameters": parameters,
                "tenant_id": tenant_id,
                "run_id": run_id,
                "approval_id": approval_id,
            },
        )
        response.raise_for_status()
        return response.json()

    @staticmethod
    def _tags(tenant_id: str, run_id: str, action_type: str) -> List[str]:
        """Tags every annotation so a dashboard can filter to this system's marks."""
        return [
            "studio-production-commander",
            f"tenant:{tenant_id}",
            f"run:{run_id}",
            f"action:{action_type}",
        ]

    async def annotate_remediation(
        self,
        tenant_id: str,
        run_id: str,
        approval_id: str,
        user_id: str,
        action_type: str,
        summary: str,
    ) -> Dict[str, Any]:
        """Marks the Grafana timeline at the moment an approved action was applied.

        The annotation lands at the current instant rather than spanning a range:
        it records a discrete change, and its value is being comparable against
        the metric inflection that follows it.
        """
        text = (
            f"[Studio Production Commander] {action_type} applied to {tenant_id} "
            f"after approval by {user_id}. {summary}"
        )
        try:
            result = await self._write(
                "create_annotation",
                {
                    "text": text,
                    "tags": self._tags(tenant_id, run_id, action_type),
                    "time": int(time.time() * 1000),
                },
                tenant_id=tenant_id,
                run_id=run_id,
                approval_id=approval_id,
            )
        except Exception as exc:
            logger.warning(
                "Grafana annotation failed; remediation itself was unaffected",
                extra={"run_id": run_id, "error": str(exc)[:200]},
            )
            return {"status": "FAILED", "error": str(exc)[:200]}

        logger.info("Grafana annotation created", extra={"run_id": run_id})
        return {"status": "CREATED", "result": result.get("result")}

    async def open_incident(
        self,
        tenant_id: str,
        run_id: str,
        approval_id: str,
        title: str,
        summary: str,
        severity: str = "minor",
    ) -> Dict[str, Any]:
        """Opens a Grafana incident recording what was found and what was approved.

        Marked as a drill by default because the render farm behind it is a
        simulator. Filing a simulated outage as a live incident would put a false
        record in a system other people are on call against; the flag exists so a
        deployment backed by a real farm can turn it off deliberately.
        """
        try:
            result = await self._write(
                "create_incident",
                {
                    "title": title,
                    "severity": severity,
                    "status": "active",
                    "isDrill": settings.grafana_incident_is_drill,
                    "roomPrefix": "studio-production",
                    # Labels are key/label pairs. There is no `value` property,
                    # and a label carrying only `label` is accepted and then
                    # silently discarded -- the incident comes back with an empty
                    # label set and no error. Both halves are required. Verified
                    # against a live create_incident round trip.
                    "labels": [
                        {"key": "tenant", "label": tenant_id},
                        {"key": "run", "label": run_id},
                    ],
                    "attachCaption": summary[:200],
                },
                tenant_id=tenant_id,
                run_id=run_id,
                approval_id=approval_id,
            )
        except Exception as exc:
            logger.warning(
                "Grafana incident creation failed; remediation itself was unaffected",
                extra={"run_id": run_id, "error": str(exc)[:200]},
            )
            return {"status": "FAILED", "error": str(exc)[:200]}

        logger.info("Grafana incident opened", extra={"run_id": run_id})
        return {"status": "CREATED", "result": result.get("result")}

    async def close(self) -> None:
        await self._http_client.aclose()


grafana_writeback = GrafanaWriteBack()
